version: '3'

services:
  grav:
    build: ./
    restart: always
    ports:
      - 8080:80
    volumes:
      - grav-user:/var/www/html/user
      - grav-backup:/var/www/html/backup
      - grav-logs:/var/www/html/logs

volumes:
  grav-user:
    driver: local
    driver_opts:
      type: none
      device: grav/user
      o: bind
  grav-backup:
    driver: local
    driver_opts:
      type: none
      device: grav/backup
      o: bind
  grav-logs:
    driver: local
    driver_opts:
      type: none
      device: grav/logs
      o: bind
